#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  Flow:
    persistence:
      backendOptions:
        dbname: 'testAcme'       # adjust to your database name
        user: 'master'             # adjust to your database user
        password: 'gtnhjdbx'         # adjust to your database password

